import { MAPS, getMap } from '../shared/map';
import { MODES } from '../shared/types';
import { WEAPONS } from '../shared/weapons';
import type { Loadout, PrimaryId, RoomInfo, RoomSummary, PlayerState } from '../shared/types';

export const escapeHTML=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export const timer=(seconds:number)=>`${Math.max(0,Math.floor(seconds/60)).toString().padStart(2,'0')}:${Math.max(0,Math.floor(seconds%60)).toString().padStart(2,'0')}`;
export function mountUI(){
  $('app').innerHTML=`
  <canvas id="game-canvas" aria-label="Dustline 3D game"></canvas>
  <div id="loading"><span class="brand">DUSTLINE<span class="brand-mark">//</span></span><div class="loading-line"></div><p>Preparing the arena…</p></div>
  <div id="menu" class="menu">
    <div class="menu-shade"></div><div class="grain"></div>
    <header class="topbar"><button id="home" class="brand">DUSTLINE<span class="brand-mark">//</span><small>MULTIPLAYER</small></button><nav aria-label="Main menu"><button data-nav="play" class="active">PLAY</button><button data-nav="loadout">LOADOUT</button><button data-nav="controls">FIELD MANUAL</button></nav><div class="top-right"><span id="connection"><i></i>CONNECTING</span><button id="settings-button" class="icon-button" title="Settings" aria-label="Settings">⚙</button></div></header>
    <main id="play-panel" class="panel play-panel">
      <div class="menu-eyebrow"><span class="live-square"></span> THREE ARENAS <span class="slash">/</span> THREE WAYS TO WIN</div>
      <h1>DUST &amp;<br/>THUNDER<span>.</span></h1><p class="map-intro">Choose your ground. Bring your squad.</p>
      <div class="map-tags"><span>UP TO 16 PLAYERS</span><span>FFA / TDM / CTF</span><span>RESPAWN & REDEPLOY</span></div>
      <div class="deploy-box"><label for="callsign">YOUR CALLSIGN</label><input id="callsign" maxlength="18" autocomplete="off" spellcheck="false" placeholder="Enter callsign" required/><button id="create-lobby" class="primary large"><span>CREATE LOBBY<small>Bring your squad. Set your rules.</small></span><b>↗</b></button><button id="practice" class="secondary"><span>SOLO WARM-UP</span><small>YOU + 3 BOTS</small><b>→</b></button></div>
      <div class="join-box"><label for="room-code">HAVE AN INVITE?</label><div><input id="room-code" aria-label="Room code" maxlength="6" autocomplete="off" placeholder="ROOM CODE" spellcheck="false"/><button id="join-lobby" aria-label="Join room">JOIN →</button></div></div>
    </main>
    <aside id="rooms-panel" class="rooms-panel"><div class="section-label"><span>OPEN LOBBIES</span><button id="refresh-rooms" title="Refresh lobbies" aria-label="Refresh lobbies">↻</button></div><div id="rooms-list"><p class="empty-rooms">No open lobbies.<br/><span>Create one and make the first move.</span></p></div></aside>
    <section id="lobby-panel" class="panel lobby-panel hidden"><div class="menu-eyebrow"><span class="live-square"></span> PRE-MATCH LOBBY <span class="slash">/</span> <span id="lobby-map-label">THE YARD</span></div><div class="lobby-heading"><h1>YOUR SQUAD<span>.</span></h1><button id="leave-lobby" class="text-button">LEAVE LOBBY ↗</button></div><div class="lobby-grid"><div class="roster-card"><div class="section-label"><span id="lobby-mode-label">FREE-FOR-ALL</span><span id="player-count"></span></div><div id="roster"></div><div class="invite-line"><span>ROOM CODE <strong id="invite-code"></strong></span><button id="copy-invite">COPY INVITE ↗</button></div></div><div class="match-card"><div class="section-label">MATCH SETUP</div><div class="map-thumb"><div class="contour"></div><span>09</span><strong id="map-title">THE YARD</strong><small id="map-description">DESERT EXTRACTION SITE</small></div><div class="setting-row"><label for="map-select">MAP</label><select id="map-select">${Object.values(MAPS).map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></div><div class="setting-row"><label for="mode-select">MODE</label><select id="mode-select"><option value="ffa">Free-for-all · 8 players</option><option value="tdm">Team deathmatch · 8v8</option><option value="ctf">Capture the flag · 8v8</option></select></div><p id="mode-description" class="muted"></p><div class="setting-row"><label for="bot-count">BOTS</label><select id="bot-count"><option value="0">No bots</option><option value="1">1 bot</option><option value="2">2 bots</option><option value="3">3 bots</option><option value="4">4 bots</option><option value="5">5 bots</option></select></div><div class="setting-row"><label for="score-limit">SCORE LIMIT</label><select id="score-limit"><option value="10">10 eliminations</option><option value="20">20 eliminations</option><option value="30">30 eliminations</option></select></div><div class="setting-row"><label for="time-limit">TIME LIMIT</label><select id="time-limit"><option value="180">3 minutes</option><option value="360">6 minutes</option><option value="600">10 minutes</option></select></div><button id="start-match" class="primary large"><span>DEPLOY TO THE YARD</span><b>→</b></button><button id="ready-button" class="primary large hidden">READY UP →</button><p id="lobby-hint" class="muted"></p></div></div></section>
    <section id="loadout-panel" class="panel loadout-panel hidden"><div class="menu-eyebrow">ARMORY <span class="slash">/</span> CUSTOM LOADOUT</div><h1>YOUR EDGE<span>.</span></h1><div class="loadout-layout"><div class="weapon-list"><div class="section-label">01 / PRIMARY WEAPON</div>${(['intervention','ak47','scar'] as PrimaryId[]).map((id,i)=>`<button class="weapon-select" data-weapon="${id}"><span class="weapon-number">0${i+1}</span><span><strong>${WEAPONS[id].shortName}</strong><small>${WEAPONS[id].category.toUpperCase()}</small></span><i>↗</i></button>`).join('')}<div class="secondary-loadout"><div class="section-label">ALWAYS EQUIPPED</div><div><kbd>2</kbd><strong>M9</strong><span>15-ROUND SIDEARM</span></div><div><kbd>3</kbd><strong>COMBAT KNIFE</strong><span>ONE-HIT MELEE</span></div></div></div><div class="weapon-stage"><div class="weapon-stage-heading"><span id="weapon-category"></span><span>FIELD READY <i class="live-square"></i></span></div><canvas id="weapon-preview" aria-label="Selected weapon preview"></canvas><div class="weapon-description"><div><h2 id="weapon-name"></h2><p id="weapon-description"></p></div><div id="weapon-stats"></div></div></div></div><button id="save-loadout" class="primary save-loadout">EQUIP LOADOUT <span>→</span></button></section>
    <section id="controls-panel" class="panel controls-panel hidden"><div class="menu-eyebrow">FIELD MANUAL <span class="slash">/</span> KNOW YOUR CONTROLS</div><h1>STAY SHARP<span>.</span></h1><div class="controls-grid"><article><h3>MOVEMENT</h3><p><span>Move</span><kbd>W A S D</kbd></p><p><span>Sprint</span><kbd>SHIFT</kbd></p><p><span>Jump</span><kbd>SPACE</kbd></p><p><span>Crouch / slide while sprinting</span><kbd>C / CTRL</kbd></p></article><article><h3>COMBAT</h3><p><span>Fire / melee</span><kbd>LMB</kbd></p><p><span>Aim down sights</span><kbd>HOLD RMB</kbd></p><p><span>Reload</span><kbd>R</kbd></p><p><span>Primary / pistol / knife</span><kbd>1 / 2 / 3</kbd></p><p><span>Quick melee / swap weapon</span><kbd>V / Q</kbd></p></article><article><h3>IN THE FIELD</h3><p><span>Scoreboard</span><kbd>HOLD TAB</kbd></p><p><span>Release mouse / menu</span><kbd>ESC</kbd></p><div class="field-note"><strong>QUICKSCOPING</strong><span>Hold right mouse to snap into the Intervention scope, then fire as the reticle settles. Accuracy locks in at 160 ms.</span></div><div class="field-note"><strong>KEEP YOUR MOMENTUM</strong><span>Hold Shift and move forward, then press C to slide into cover. Release C to stand after the slide.</span></div></article></div></section>
    <footer class="menu-footer"><button id="footer-loadout"><span class="slot-number">01</span><span><small>ACTIVE LOADOUT</small><strong id="active-primary">INTERVENTION</strong></span><span class="footer-secondary">M9 / KNIFE</span><b>↗</b></button><div class="map-caption"><span>THREE ARENAS</span><small>THE YARD / FOUNDRY / RELAY</small><i>03</i></div><a class="asset-credits" href="/credits.html" target="_blank" rel="noopener">ART CREDITS ↗</a><span class="build-label">MULTIPLAYER · v2.0</span></footer>
  </div>
  <div id="hud" class="hidden"><div class="hud-top"><div class="minimap-wrap"><canvas id="minimap" width="176" height="176"></canvas><span id="minimap-name">THE YARD</span><b>N</b></div><div class="match-status"><span id="hud-mode">FREE-FOR-ALL</span><div id="team-score" class="team-score hidden"></div><strong id="match-timer">06:00</strong><small>FIRST TO <b id="hud-limit">20</b></small></div><div class="hud-network"><span id="hud-ping">0 MS</span><span id="hud-fps">60 FPS</span></div></div><div id="objective-hud" class="objective-hud hidden"></div><div id="killfeed"></div><div id="crosshair"><i></i><i></i><i></i><i></i><b></b></div><div id="scope" class="hidden"><div class="scope-lens"><div class="scope-horizontal"></div><div class="scope-vertical"></div><div class="scope-ticks"></div><i></i><span>7× / INTERVENTION</span></div></div><div id="hitmarker"><i></i><i></i><i></i><i></i></div><div id="damage-vignette"></div><div id="kill-notice"><strong></strong><span></span></div><div id="action-notice"></div><div class="hud-bottom"><div class="health-panel"><div><span class="health-cross">+</span><strong id="health">100</strong><span id="stance">READY</span></div><div class="health-track"><i id="health-bar"></i></div><small id="hud-name"></small><span id="personal-score">0 K / 0 D</span></div><div class="hud-controls"><span><kbd>SHIFT</kbd> SPRINT</span><span><kbd>C</kbd> SLIDE</span><span><kbd>TAB</kbd> SCORE</span></div><div class="ammo-panel"><div id="hud-weapon">INTERVENTION</div><div class="ammo-count"><strong id="ammo">05</strong><span>/ <b id="reserve">25</b></span></div><div class="weapon-slots"><span id="slot-0" class="selected"><kbd>1</kbd> PRIMARY</span><span id="slot-1"><kbd>2</kbd> M9</span><span id="slot-2"><kbd>3</kbd> KNIFE</span></div></div></div><div id="respawn" class="hidden"><small>ELIMINATED</small><h2>BACK IN THE FIGHT</h2><strong id="respawn-count">3</strong><span id="killer-name"></span></div></div>
  <div id="pause" class="overlay hidden"><div class="pause-card"><div id="pause-match" class="menu-eyebrow">THE YARD / FREE-FOR-ALL</div><h2>STAY IN THE FIGHT<span>.</span></h2><p>The match continues while your mouse is released.</p><button id="resume" class="primary large">CLICK TO PLAY <b>→</b></button><button id="pause-settings" class="secondary">SETTINGS <b>↗</b></button><button id="quit-match" class="text-button">LEAVE MATCH</button><div class="pause-key-hints">WASD move · Shift sprint · C slide · RMB aim</div></div></div>
  <div id="scoreboard" class="overlay hidden"><div class="scoreboard-card"><div class="section-label"><span id="scoreboard-match">THE YARD / FREE-FOR-ALL</span><span id="scoreboard-room"></span></div><h2 id="scoreboard-title">SCOREBOARD</h2><div class="scoreboard-header"><span>OPERATOR</span><span>KILLS</span><span>DEATHS</span><span>K/D</span></div><div id="scoreboard-rows"></div><div id="post-match" class="hidden"><p id="winner-text"></p><button id="return-lobby" class="primary large">RETURN TO LOBBY <b>→</b></button><button id="post-leave" class="text-button">LEAVE LOBBY</button></div></div></div>
  <div id="settings" class="overlay hidden"><div class="settings-card"><div class="section-label"><span>SETTINGS</span><button id="close-settings" aria-label="Close settings">✕</button></div><h2>MAKE IT YOURS<span>.</span></h2><label class="range-setting">MOUSE SENSITIVITY <output id="sensitivity-value">1.0</output><input id="sensitivity" type="range" min="0.2" max="2.5" step="0.1" value="1"/></label><label class="range-setting">FIELD OF VIEW <output id="fov-value">82°</output><input id="fov" type="range" min="70" max="105" step="1" value="82"/></label><label class="range-setting">VOLUME <output id="volume-value">45%</output><input id="volume" type="range" min="0" max="100" step="1" value="45"/></label><div class="setting-row"><label for="quality">GRAPHICS</label><select id="quality"><option value="high">High · shadows on</option><option value="low">Performance</option></select></div><div class="setting-row"><label for="latency">ADDED NETWORK DELAY</label><select id="latency"><option value="0">None</option><option value="80">80 ms round trip</option><option value="160">160 ms round trip</option><option value="250">250 ms round trip</option></select></div><p class="muted">Added delay lets you try movement and gunplay on a slower connection.</p><button id="settings-done" class="primary large">DONE <b>✓</b></button></div></div>
  <div id="toast" role="status" aria-live="polite"></div><div id="webgl-error" class="overlay hidden"><div class="pause-card"><h2>WebGL is unavailable</h2><p>Enable hardware acceleration in your browser, then reload to play.</p><button onclick="location.reload()" class="primary">RELOAD</button></div></div>`;
}
export function paintLoadout(loadout:Loadout){
  const w=WEAPONS[loadout.primary];
  document.querySelectorAll<HTMLElement>('[data-weapon]').forEach(b=>b.classList.toggle('selected',b.dataset.weapon===loadout.primary));
  $('active-primary').textContent=w.shortName;$('weapon-category').textContent=w.category.toUpperCase();$('weapon-name').textContent=w.shortName;
  const descriptions:Record<PrimaryId,string>={intervention:'One round. One elimination. A fast 160 ms scope-in and a bolt that makes every shot count.',ak47:'Hard-hitting, full-auto firepower. Thirty rounds of close-quarters confidence.',scar:'Heavy rounds. Measured recoil. Control the long sightlines with fewer shots.'};
  $('weapon-description').textContent=descriptions[loadout.primary];
  const stats=[['DAMAGE',w.damage,100],['FIRE RATE',Math.round(60/w.fireInterval),650],['MOBILITY',loadout.primary==='intervention'?62:loadout.primary==='ak47'?85:76,100]] as [string,number,number][];
  $('weapon-stats').innerHTML=stats.map(([name,v,max])=>`<div class="stat"><span>${name}</span><i><b style="width:${Math.min(100,v/max*100)}%"></b></i><small>${v}</small></div>`).join('')+`<div class="weapon-spec"><span>${w.mag} ROUNDS</span><span>${Math.round(w.adsTime*1000)} MS ADS</span></div>`;
}
export function paintRooms(rooms:RoomSummary[]){$('rooms-list').innerHTML=rooms.length?rooms.map(r=>`<button class="room-item" data-room="${escapeHTML(r.code)}"><span><strong>${escapeHTML(r.name)}</strong><small>${r.state==='playing'?'IN PROGRESS':'IN LOBBY'} · ${escapeHTML(getMap(r.map).name.toUpperCase())} · ${r.mode.toUpperCase()}</small></span><b>${r.players}/${r.maxPlayers}</b><i>↗</i></button>`).join(''):'<p class="empty-rooms">No open lobbies.<br/><span>Create one and make the first move.</span></p>';}
export function paintLobby(room:RoomInfo,id:string){
  const host=room.host===id, me=room.players.find(p=>p.id===id), map=getMap(room.map), mode=MODES[room.mode];
  $('invite-code').textContent=room.code;$('player-count').textContent=`${room.players.length+room.bots} / ${room.maxPlayers} OPERATORS`;
  $('lobby-mode-label').textContent=mode.name.toUpperCase();$('lobby-map-label').textContent=map.name.toUpperCase();
  $('map-title').textContent=map.name.toUpperCase();$('map-description').textContent=room.mode==='ffa'?'EVERY OPERATOR FOR THEMSELVES':'RED vs BLUE · 8 PER TEAM';
  $('mode-description').textContent=room.mode==='ctf'?'Steal the enemy flag and bring it home. Your flag must be at base to capture. Touch a dropped friendly flag to return it.':room.mode==='tdm'?'Team eliminations count toward victory. Friendly fire is off.':'Every elimination counts. First to the score limit wins.';
  const row=(p:RoomInfo['players'][number],i:number)=>`<div class="player-row ${p.id===id?'you':''} team-${p.team||'none'}"><span class="operator-badge">${p.team?p.team==='red'?'R':'B':String(i+1).padStart(2,'0')}</span><span class="player-detail"><strong>${escapeHTML(p.name)} ${p.id===id?'<small>YOU</small>':''}</strong><span>${p.team?p.team.toUpperCase()+' TEAM · ':''}${WEAPONS[p.loadout.primary].shortName}</span></span><span class="player-ready ${p.ready||p.id===room.host?'is-ready':''}">${!p.connected?'RECONNECTING':p.id===room.host?'HOST':p.ready?'READY':'NOT READY'}</span></div>`;
  $('roster').innerHTML=[...room.players].sort((a,b)=>(a.team||'').localeCompare(b.team||'')).map(row).join('')+Array.from({length:room.bots},(_,i)=>`<div class="player-row bot"><span class="operator-badge">AI</span><span class="player-detail"><strong>BOT ${String(i+1).padStart(2,'0')}</strong><span>BOT OPERATOR</span></span><span class="player-ready is-ready">READY</span></div>`).join('')+`<div class="empty-slot"><span>+</span> ${Math.max(0,room.maxPlayers-room.players.length-room.bots)} OPEN SLOTS</div>`;
  $<HTMLSelectElement>('bot-count').innerHTML=Array.from({length:Math.max(1,room.maxPlayers-room.players.length+1)},(_,i)=>`<option value="${i}">${i===0?'No bots':i+' bot'+(i===1?'':'s')}</option>`).join('');
  const limits=room.mode==='ctf'?[1,3,5,10]:room.mode==='tdm'?[20,50,75,100]:[10,20,30,50];
  if(!limits.includes(room.limit))limits.push(room.limit);
  $<HTMLSelectElement>('score-limit').innerHTML=limits.sort((a,b)=>a-b).map(n=>`<option value="${n}">${n} ${room.mode==='ctf'?'captures':'eliminations'}</option>`).join('');
  $<HTMLSelectElement>('bot-count').value=String(room.bots);$<HTMLSelectElement>('score-limit').value=String(room.limit);$<HTMLSelectElement>('time-limit').value=String(room.duration);
  $<HTMLSelectElement>('map-select').value=room.map;$<HTMLSelectElement>('mode-select').value=room.mode;
  ['bot-count','score-limit','time-limit','map-select','mode-select'].forEach(key=>$<HTMLSelectElement>(key).disabled=!host);
  $('start-match').classList.toggle('hidden',!host);$('start-match').innerHTML=`<span>DEPLOY TO ${escapeHTML(map.name.toUpperCase())}</span><b>→</b>`;
  $('ready-button').classList.toggle('hidden',host);$('ready-button').textContent=me?.ready?'READY ✓ · CLICK TO UNREADY':'READY UP →';
  const allReady=room.players.every(p=>p.connected&&(p.ready||p.id===room.host));
  $<HTMLButtonElement>('start-match').disabled=room.state==='lobby'&&!allReady;
  $('lobby-hint').textContent=host?(allReady?'Your lobby is ready. Deploy when you are.':'Waiting for every operator to ready up.'):'The host will start when everyone is ready.';
}
export function paintScoreboard(players:PlayerState[],id:string){
  const teamGame=players.some(p=>p.team);
  const sorted=[...players].sort((a,b)=>(teamGame?(a.team||'').localeCompare(b.team||''):0)||b.captures-a.captures||b.kills-a.kills||a.deaths-b.deaths);
  $('scoreboard-rows').innerHTML=sorted.map((p,i)=>`<div class="score-row ${p.id===id?'you':''} team-${p.team||'none'}"><span><i>${p.team?p.team==='red'?'R':'B':String(i+1).padStart(2,'0')}</i><strong>${escapeHTML(p.name)}</strong>${p.captures?`<small>${p.captures} CAP</small>`:''}${p.id===id?'<small>YOU</small>':p.bot?'<small>BOT</small>':''}</span><b>${p.kills}</b><b>${p.deaths}</b><b>${(p.kills/Math.max(1,p.deaths)).toFixed(2)}</b></div>`).join('');
}
